"""
zk_snark.py — Groth16 eligibility proof engine for IoToDChain.

The patient attributes (age, HbA1c, CKD) are private witness values.
Only two public values are bound to the proof:
  1) ProofPolicyID hash
  2) ciphertext hash (hEncM)

The API never stores the witness in blockchain records.
Artifacts are generated by setup_zk.sh.
"""

from __future__ import annotations

import hashlib
import json
import os
import subprocess
import tempfile
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any


BASE_DIR = Path(__file__).resolve().parent
ZK_DIR = BASE_DIR / "zk"
CIRCUIT_DIR = ZK_DIR / "eligibility_js"
WASM = CIRCUIT_DIR / "eligibility.wasm"
ZKEY = ZK_DIR / "eligibility_final.zkey"
VKEY = ZK_DIR / "verification_key.json"

# BN128 scalar field modulus used by Circom/snarkjs.
BN128_FIELD = 21888242871839275222246405745257275088548364400416034343698204186575808495617


class ZKConfigurationError(RuntimeError):
    pass


class ZKProofError(RuntimeError):
    pass


def _sha256_hex(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def _field_from_hex(hex_digest: str) -> str:
    return str(int(hex_digest, 16) % BN128_FIELD)


def canonical_policy(policy_id: str, condition: str) -> str:
    return json.dumps(
        {"ProofPolicyID": policy_id, "condition": condition},
        sort_keys=True,
        separators=(",", ":"),
    )


@dataclass
class EligibilityInput:
    age: int
    hba1c: float
    ckd: int

    def validate(self) -> None:
        if not 0 <= self.age <= 255:
            raise ValueError("age must be in [0,255]")
        if self.hba1c < 0 or self.hba1c > 100:
            raise ValueError("HbA1c must be in [0,100]")
        if self.ckd not in (0, 1):
            raise ValueError("CKD must be 0 or 1")


class ZKSnarkEngine:
    def __init__(self) -> None:
        self._check_artifacts()

    def _check_artifacts(self) -> None:
        missing = [str(p) for p in (WASM, ZKEY, VKEY) if not p.exists()]
        if missing:
            raise ZKConfigurationError(
                "ZK artifacts are missing. Run ./setup_zk.sh first. Missing: "
                + ", ".join(missing)
            )

    @staticmethod
    def _run(cmd: list[str], cwd: Path | None = None) -> subprocess.CompletedProcess:
        try:
            return subprocess.run(
                cmd,
                cwd=str(cwd) if cwd else None,
                check=True,
                capture_output=True,
                text=True,
            )
        except FileNotFoundError as exc:
            raise ZKConfigurationError(
                f"Required executable is not installed: {cmd[0]}"
            ) from exc
        except subprocess.CalledProcessError as exc:
            detail = (exc.stderr or exc.stdout or "").strip()
            raise ZKProofError(f"Command failed: {' '.join(cmd)}\n{detail}") from exc

    def _input(
        self,
        private_input: EligibilityInput,
        proof_policy_id: str,
        ct_hash: str,
        condition: str,
    ) -> tuple[dict[str, str], str, str]:
        private_input.validate()
        policy_digest = _sha256_hex(canonical_policy(proof_policy_id, condition))
        ct_digest = ct_hash.lower().replace("0x", "")
        if len(ct_digest) != 64 or any(c not in "0123456789abcdef" for c in ct_digest):
            raise ValueError("ct_hash must be a 64-character SHA-256 hex digest")

        data = {
            "age": str(private_input.age),
            "hba1c10": str(round(private_input.hba1c * 10)),
            "ckd": str(private_input.ckd),
            "policyHash": _field_from_hex(policy_digest),
            "ctHash": _field_from_hex(ct_digest),
        }
        return data, policy_digest, ct_digest

    def prove(
        self,
        private_input: EligibilityInput,
        proof_policy_id: str,
        ct_hash: str,
        condition: str,
    ) -> dict[str, Any]:
        data, policy_digest, ct_digest = self._input(
            private_input, proof_policy_id, ct_hash, condition
        )

        # The circuit enforces eligible === 1, therefore an ineligible witness
        # intentionally fails during witness generation/proving.
        with tempfile.TemporaryDirectory(prefix="iotodchain-zk-") as tmp:
            t = Path(tmp)
            input_json = t / "input.json"
            witness = t / "witness.wtns"
            proof = t / "proof.json"
            public = t / "public.json"

            input_json.write_text(json.dumps(data), encoding="utf-8")

            self._run([
                "node", str(CIRCUIT_DIR / "generate_witness.js"),
                str(WASM), str(input_json), str(witness),
            ])
            self._run([
                "snarkjs", "groth16", "prove",
                str(ZKEY), str(witness), str(proof), str(public),
            ])

            proof_obj = json.loads(proof.read_text(encoding="utf-8"))
            public_values = json.loads(public.read_text(encoding="utf-8"))

        return {
            "proof": proof_obj,
            "public": public_values,
            "policy_hash": policy_digest,
            "ct_hash": ct_digest,
            "proof_policy_id": proof_policy_id,
        }

    def verify(
        self,
        proof_obj: dict[str, Any],
        public_values: list[Any],
        proof_policy_id: str,
        ct_hash: str,
        condition: str,
    ) -> bool:
        expected_policy = _field_from_hex(
            _sha256_hex(canonical_policy(proof_policy_id, condition))
        )
        expected_ct = _field_from_hex(ct_hash.lower().replace("0x", ""))

        # Public signal order is defined by:
        # component main {public [policyHash, ctHash]} = Eligibility();
        if len(public_values) != 2:
            return False
        if str(public_values[0]) != expected_policy:
            return False
        if str(public_values[1]) != expected_ct:
            return False

        with tempfile.TemporaryDirectory(prefix="iotodchain-zk-verify-") as tmp:
            t = Path(tmp)
            proof_path = t / "proof.json"
            public_path = t / "public.json"
            proof_path.write_text(json.dumps(proof_obj), encoding="utf-8")
            public_path.write_text(json.dumps(public_values), encoding="utf-8")

            result = self._run([
                "snarkjs", "groth16", "verify",
                str(VKEY), str(public_path), str(proof_path),
            ])
            return "OK!" in (result.stdout or "")

    def prove_and_verify(
        self,
        private_input: EligibilityInput,
        proof_policy_id: str,
        ct_hash: str,
        condition: str,
    ) -> dict[str, Any]:
        started = time.perf_counter()
        artifact = self.prove(private_input, proof_policy_id, ct_hash, condition)
        prove_ms = (time.perf_counter() - started) * 1000

        started = time.perf_counter()
        verified = self.verify(
            artifact["proof"],
            artifact["public"],
            proof_policy_id,
            ct_hash,
            condition,
        )
        verify_ms = (time.perf_counter() - started) * 1000

        return {
            **artifact,
            "verified": verified,
            "prove_ms": round(prove_ms, 3),
            "verify_ms": round(verify_ms, 3),
        }
