import csv
import json
import os
import subprocess
import time
from cryptography.fernet import Fernet

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# Target Record Sizes in MB
RECORD_SIZES_MB = [0.2, 0.5, 1.0, 4.0, 7.0, 10.0, 14.0, 17.0, 20.0]


def find_file(filename):
    """Recursively find files in project directory."""
    for root, _, files in os.walk(BASE_DIR):
        if filename in files:
            return os.path.join(root, filename)
    return None


def run_cmd(cmd):
    """Executes system command and returns exact wall-clock time in ms."""
    t0 = time.perf_counter()
    res = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    t1 = time.perf_counter()
    if res.returncode != 0:
        raise RuntimeError(f"Command failed: {cmd}\nError: {res.stderr}")
    return (t1 - t0) * 1000.0


def run_real_benchmark():
    witness_js = find_file("generate_witness.js")
    wasm_file = find_file("eligibility.wasm") or find_file("circuit.wasm")
    input_file = find_file("input.json") or os.path.join(BASE_DIR, "input.json")
    groth16_zkey = find_file("circuit_final_groth16.zkey") or os.path.join(
        BASE_DIR, "circuit_final_groth16.zkey"
    )

    # Fail immediately if ZK files are missing (No mock values allowed)
    if not (
        witness_js
        and wasm_file
        and os.path.exists(groth16_zkey)
        and os.path.exists(input_file)
    ):
        raise FileNotFoundError(
            f"\n[ERROR] Missing ZK setup artifacts!\n"
            f"Found witness_js : {witness_js}\n"
            f"Found wasm_file   : {wasm_file}\n"
            f"Found groth16_zkey: {os.path.exists(groth16_zkey)}\n"
            f"Found input_file  : {os.path.exists(input_file)}\n\n"
            f"Please run the setup commands in PowerShell first!"
        )

    results = []

    print("=" * 70)
    print("EXECUTING REAL BENCHMARK ON LOCAL HARDWARE")
    print("=" * 70)

    for size in RECORD_SIZES_MB:
        print(f"\nBenchmarking record payload: {size} MB...")

        # 1. Real Encryption & Decryption Timing on generated byte stream
        raw_bytes = os.urandom(int(size * 1024 * 1024))
        key = Fernet.generate_key()
        cipher = Fernet(key)

        # Measure Encryption
        t0 = time.perf_counter()
        cipher_bytes = cipher.encrypt(raw_bytes)
        t1 = time.perf_counter()
        enc_time_ms = (t1 - t0) * 1000.0

        # Measure Decryption
        t0 = time.perf_counter()
        _ = cipher.decrypt(cipher_bytes)
        t1 = time.perf_counter()
        dec_time_ms = (t1 - t0) * 1000.0

        # 2. Real ZK Witness Generation Timing
        witness_file = os.path.join(BASE_DIR, f"witness_{size}MB.wtns")
        proof_file = os.path.join(BASE_DIR, f"proof_{size}MB.json")
        public_file = os.path.join(BASE_DIR, f"public_{size}MB.json")
        vkey_file = os.path.join(BASE_DIR, f"vkey_{size}MB.json")

        wit_time_ms = run_cmd(
            f'node "{witness_js}" "{wasm_file}" "{input_file}" "{witness_file}"'
        )

        # 3. Real Groth16 Proving Timing
        proof_time_ms = run_cmd(
            f'npx snarkjs groth16 prove "{groth16_zkey}" "{witness_file}" "{proof_file}" "{public_file}"'
        )

        # 4. Real Proof Verification Timing
        if not os.path.exists(vkey_file):
            run_cmd(
                f'npx snarkjs zkey export verificationkey "{groth16_zkey}" "{vkey_file}"'
            )

        verify_time_ms = run_cmd(
            f'npx snarkjs groth16 verify "{vkey_file}" "{public_file}" "{proof_file}"'
        )

        snark_proving_ms = wit_time_ms + proof_time_ms
        total_time_ms = (
            enc_time_ms + dec_time_ms + snark_proving_ms + verify_time_ms
        )

        results.append(
            {
                "Record Size (MB)": size,
                "Encryption (ms)": round(enc_time_ms, 4),
                "Decryption (ms)": round(dec_time_ms, 4),
                "zk-SNARK Proving (ms)": round(snark_proving_ms, 4),
                "zk-SNARK Verify (ms)": round(verify_time_ms, 4),
                "Total Execution (ms)": round(total_time_ms, 4),
            }
        )

    # Export pure benchmark results to CSV
    csv_path = os.path.join(BASE_DIR, "real_evaluation_results.csv")
    with open(csv_path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=results[0].keys())
        writer.writeheader()
        writer.writerows(results)

    print("\n" + "=" * 70)
    print("PURE LOCAL HARDWARE BENCHMARK RESULTS")
    print("=" * 70)
    print(
        "| Record Size (MB) | Encryption (ms) | Decryption (ms) | zk-SNARK Proving (ms) | zk-SNARK Verify (ms) | Total Execution (ms) |"
    )
    print("| :---: | :---: | :---: | :---: | :---: | :---: |")
    for r in results:
        print(
            f"| **{r['Record Size (MB)']}** | {r['Encryption (ms)']:.4f} | {r['Decryption (ms)']:.4f} | {r['zk-SNARK Proving (ms)']:.4f} | {r['zk-SNARK Verify (ms)']:.4f} | **{r['Total Execution (ms)']:.4f}** |"
        )


if __name__ == "__main__":
    run_real_benchmark()